trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0'
  inputs:
    packageType: sdk
    version: 5.0.203
    installationPath: $(Agent.ToolsDirectory)\dotnet

- task: CmdLine@2
  displayName: 'Install h5 compiler'
  inputs:
    script: 'dotnet tool install --global h5-compiler'

- task: CmdLine@2
  displayName: 'build and publish'
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    script: |
      pushd H5.Dist
      dotnet restore
      dotnet build -c Release
      popd
      mkdir dist
      pushd dist
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.meta.min.js 
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.min.js
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.js
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.meta.js
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\newtonsoft.json.js
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\newtonsoft.json.min.js
      dir /s
      popd

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'publish --access public --verbose'
    customEndpoint: 'npm theolivenbaum'
