trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0'
  inputs:
    packageType: sdk
    version: 5.0.203
    installationPath: $(Agent.ToolsDirectory)\dotnet

- task: CmdLine@2
  displayName: 'Install h5 compiler'
  inputs:
    script: 'dotnet tool install --global h5-compiler'

- task: CmdLine@2
  displayName: 'build and publish'
  inputs:
    workingDirectory: $(Build.SourcesDirectory)
    script: |
      pushd H5.Dist
      dotnet restore
      dotnet build -c Release
      popd
      mkdir dist
      pushd dist
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.meta.min.js 
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.min.js
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.js
      xcopy ..\H5.Dist\bin\Release\netstandard2.0\h5\h5.meta.js
      popd
      echo "login to npm //registry.npmjs.org/:_authToken"
      npm install
      npm set //registry.npmjs.org/:_authToken $(NPM_TOKEN)
      echo "publishing package"
      npm publish --access public --verbose
      echo "done!"
